Starting assignment 4
ShaunWMusic/04-surf-and-paddle pull request #1
Opened 2016-09-29 21:50 UTC by ShaunWMusic

2016-10-06 13:46 UTC, ShaunWMusic commented
* [ ] Follow the homework checklist to create and start project.
* [ ] **GOAL**: Site Header/Hero
  - [ ] Checkpoint: Create markup for Header/Hero
    * [ ] Markup: Navbar
      - [ ] Markup: Navbar Logo
      - [ ] Markup: About Link
      - [ ] Markup: Search Link
    * [ ] Markup: Hero Title ("Surf & Paddle Co")
    * [ ] Markup: Hero Sub Title ("An Ironyard Academy Project Est Fall 2013")
  - [ ] Checkpoint: Style for Header/Hero
    * [ ] Style: Banner Background
    * [ ] Style: Navbar Logo
    * [ ] Style: Navbar About
    * [ ] Style: Navbar Search
    * [ ] Style: Hero Text
    * [ ] Style: Hero Subtitle
* [ ] **GOAL**: Site Main
  - [ ] Checkpoint: Create markup for Site Main
    * [ ] Markup: Left Article
      - [ ] Markup: Article Heading
      - [ ] Markup: Article Author Avatar
      - [ ] Markup: Article Publish Date
      - [ ] Markup: Article text
      - [ ] Markup: Article quote
    * [ ] Markup: Right Article Details
      - [ ] Markup: Author Image
      - [ ] Markup: Author Name
      - [ ] Markup: Author Social Links
      - [ ] Markup: Ad Image
      - [ ] Markup: Ad Link
      - [ ] Markup: Sidebar 2nd Article Link
      - [ ] Markup: Sidebar 2nd Article Short
  - [ ] Checkpoint: Style for Site Main
    * [ ] Style: Left Article
      - [ ] Style: Article Heading
      - [ ] Style: Article Author Avatar
      - [ ] Style: Article Publish Date
      - [ ] Style: Article text
      - [ ] Style: Article quote
    * [ ] Style: Right Article Details
      - [ ] Style: Author Image
      - [ ] Style: Author Name
      - [ ] Style: Author Social Links
      - [ ] Style: Ad Image
      - [ ] Style: Ad Link
      - [ ] Style: Sidebar 2nd Article Link
      - [ ] Style: Sidebar 2nd Article Short
*[ ] **GOAL**: Site Footer
  - [ ] Checkpoint: Create markup for Site Footer
    * [ ] Markup: Footer heading
    * [ ] Markup: Footer Other Posts (Images)
      - [ ] Markup: Footer Other Post Item Picture
      - [ ] Markup: Footer Other Post Item Title
    * [ ] Markup: Footer Navbar
      - [ ] Markup: Footer Navbar Logo
      - [ ] Markup: Footer Navbar Legal
      - [ ] Markup: Footer Navbar Nav Items
  - [ ] Checkpoint: Style Site Footer
    * [ ] Style: Footer heading
    * [ ] Style: Footer Other Posts (Images)
      - [ ] Style: Footer Other Post Item Picture
      - [ ] Style: Footer Other Post Item Title
    * [ ] Style: Footer Navbar
      - [ ] Style: Footer Navbar Logo
      - [ ] Style: Footer Navbar Legal
      - [ ] Style: Footer Navbar Nav Items

2016-10-06 23:59 UTC, rtablada requested changes
The footer at the bottom should have a full width background color and the content should be contained to the same max width as the top nav and main content.

<img width="1680" alt="screen shot 2016-10-06 at 6 59 08 pm" src="https://cloud.githubusercontent.com/assets/2532004/19174764/fc4fe4a0-8bf6-11e6-90d4-714c72e6bd10.png">

The rest is pretty close with a few of the noted changes above.

2016-10-06 23:59 UTC, rtablada commented on app.css
> +  max-width: 60%;
This should be in `rem` values not percentages so that the container sizes are even throughout the app.

2016-10-06 23:59 UTC, rtablada commented on app.css
> +.img-header {
I think one thing that is making this hard to position is the default margin.

Once you do this, use top and left if you want the text to be pinned close to the top left edge.

2016-10-06 23:59 UTC, rtablada commented on app.css
> +  width: 100%;
If you set a height (like 18 or 20 rems) you can then use `object-fit: cover` to make all of the images the same size without changing the aspect ratio.

2016-10-06 23:59 UTC, rtablada commented on index.html
> +<hr class="divider">
This can be easier accomplished by putting a border top on the footer section.

Either way it should span across the full width of the page.

2016-10-08 10:38 UTC, ShaunWMusic commented on index.html
> +<hr class="divider">
ok, I changed this to border-top in footer. :)

2016-10-08 11:10 UTC, ShaunWMusic commented on app.css
> +  max-width: 60%;
max-width is now is rem.

2016-10-08 11:21 UTC, ShaunWMusic commented on app.css
> +  width: 100%;
i applied 18rem to height, and object-fit:cover to images and it sized everything to fit.

2016-10-08 11:22 UTC, ShaunWMusic commented on app.css
> +  max-width: 60%;
but once i apply background color, you see white space on left and right of footer in desktop view?

2016-10-09 19:50 UTC, rtablada requested changes
![screen shot 2016-10-09 at 2 45 09 pm](https://cloud.githubusercontent.com/assets/2532004/19223200/bb3dd676-8e2f-11e6-9365-7ab67d7c7ed1.png)

2016-10-09 19:50 UTC, rtablada commented on index.html
> +      <div class="container__logo">
Very close here, just one more wrapper, where the background down here on the footer should be across the page at all widths. I think you could rename or restyle this existing HTML to get this effect.

So name this outer div `logo` and give it the padding and background color.
Then name the inner div `logo__container` which only has the display flex and max-width and margin auto.

2016-10-09 22:17 UTC, ShaunWMusic commented on app.css
> +  max-width: 60%;
@rtablada i made the changes to the footer like you mentioned!

2016-10-12 20:37 UTC, rtablada requested changes

2016-10-12 20:37 UTC, rtablada commented on index.html
> +        <img src="img/the-iron-yard-logo.png" alt="" class="logo-pic">
Be sure to close the `container__logo` before the nav list and then you can remove the width for `nav__list` which can help in getting the bottom nav to line up with the rest of the content on the right edge.

2016-10-18 14:50 UTC, ShaunWMusic commented on index.html
> +        <img src="img/the-iron-yard-logo.png" alt="" class="logo-pic">
@rtablada ok, so i did that, and created a spacing issue to where it doesn't line up with the top-nav.... going to look it more to see what I can do to fix it

2016-10-23 22:12 UTC, ShaunWMusic commented on index.html
> +        <img src="img/the-iron-yard-logo.png" alt="" class="logo-pic">
@rtablada I fixed the footer to match the top-nav

2017-03-09 23:28 UTC, merged